spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exprass?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: exp
    password: exprass
    # Druid 本地环境配置
    initialSize: 1
    min-idle: 0
    max-active: 10
    max-wait: 6000 # 最大等待（连接）时间，毫秒；配置后缺省启用公平锁，并发效率会有所下降，配置useUnfairLock属性为true使用非公平锁。
    use-unfair-lock: false
    validation-query: SELECT 1
    validation-query-timeout: 60
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    time-between-eviction-runs-millis: 60000 # 1min
    keep-alive: false
    min-evictable-idle-time-millis: 300000 # 连接保持空闲而不被驱逐的最小时间，超时keepAlive或关闭（Destroy线程）
    pool-prepared-statements: false # PSCache，支持游标（Oracle）时显著提升性能，mysql关闭
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    use-global-data-source-stat: true
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: localhost
    port: 6379
    auth: exprass
    database: 0
    lettuce:
      pool:
        max-wait: 30
        max-active: 10
        max-idle: 2
        min-idle: 0
        timeout: 3000
#debug: true
app:
  growing-story: # growing-story 应用配置开始
    home: # 应用主页
    baidu: # 应用集成百度开放平台 api 配置开始
      net-disk: # 集成（需注册到）百度网盘开放平台
        app-key: xV508jGyGYHDTMdG3rCZLztWTF93lcRu # 注册的 appKey
        secret-key: rybByzXGVs155EptAfCosfBFrnD3fNoP # 注册的 secretKey
        redirect-uri: # 注册的 OAuth 授权回调地址
    wechat:
    alipay:
sso:
  auth:
    unauthenticated: #http://localhost:8080/unauthenticated # 未登录页面
    unauthorized: #http://localhost:8080/unauthorized # 未授权页面